#cloud-config
# vim: syntax=yaml

# Set the host-level DNS server
manage_resolv_conf: true

resolv_conf:
  nameservers: ["192.168.1.185"]

network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true

# You could modify this for your own user information
users:
  - name: worker
    gecos: "worker"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,video,input
    lock_passwd: false
    ssh_pwauth: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC1C1WPGETJEVuIs9rdPONt0hTr9RrVdtZYDc0Zu/egd jaredallard@hachiman.local

# Set the locale of the system
locale: "en_US.UTF-8"

# Set the timezone
timezone: "UTC"

# Update apt packages on first boot
package_update: true
package_upgrade: false
package_reboot_if_required: true

# Install any additional apt packages you need here
packages:
  # Time
  - fake-hwclock
  # Networking stuff
  - resolvconf
  - ifupdown
  # Get more entropy
  - haveged
  # Bye bye hackers.
  - fail2ban
  # For DNS at home
  - avahi-daemon
  # Nice stuff
  - neovim
  # Storage
  - nfs-common

write_files:
  - content: |-
      LABEL=writable          /               ext4    defaults,noatime       0 0
      LABEL=system-boot       /boot/firmware  vfat    defaults               0 1

      # We can mount these dirs as tmpfs to save the life of our flash storage
      tmpfs /tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=0755,size=100M 0 0
      tmpfs /var/tmp tmpfs defaults,noatime,nosuid,nodev,noexec,mode=0755,size=100M 0 0
      tmpfs /var/log tmpfs defaults,noatime,nosuid,nodev,noexec,mode=0755 0 0
    path: /etc/fstab

# These commands will be ran once on first boot only
runcmd:
  # Remove packages
  - apt-get autoremove -y snapd

  # Configure ntp
  - timedatectl set-ntp true

  # Generate a hostname
  - 'uuidgen | awk -F - "{ print \$1\$2\$3 }" | tee /etc/hostname'
  - 'echo "127.0.0.1 $(cat /etc/hostname) $(cat /etc/hostname).local" >> /etc/hosts'

  # Pickup the hostname changes
  - "systemctl restart --no-block avahi-daemon"

  # Add the correct group to worker
  - "usermod -aG docker worker"

  # systemd
  - [systemctl, daemon-reload]
  - [
      systemctl,
      enable,
      --now,
      --no-block,
      avahi-daemon.service,
      haveged.service,
      fail2ban.service,
      fake-hwclock.service,
    ]

  # remove the ubuntu user(s), just in case
  - [sh, -c, "userdel ubuntu || exit 0"]
  - [sh, -c, "userdel pi || exit 0"]

  # modify the kernel commandline to support Kubernetes
  - [
      sh,
      -c,
      'echo "net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline cgroup_enable=cpuset cgroup_enable=memory rootwait fixrtc" >/boot/firmware/cmdline.txt',
    ]

  # reboot
  - reboot
